#!/usr/bin/env node
/* =========================================================================
 * Xenachord Designer — BUILD PRESETS FROM THE presets/ FOLDER
 * =========================================================================
 *
 * The presets/ folder is the drag-and-drop preset library: drop a
 * "Save Layout File (.json)" download in there to add a preset, delete the
 * file to remove one, rename it to rename the preset. Each file already
 * carries the full session it was saved with — tuning/notation and
 * timbre/synth — because that is what "Save Layout File" writes (see
 * share.js's fileFor/playNow).
 *
 * This script reads every *.json in presets/ and regenerates
 * presets-shared.js in the exact format the app's own "Write Presets File"
 * button writes, so the app needs no changes to pick these up — it already
 * reads window.XENACHORD_PRESETS from that file.
 *
 * Run it after editing the folder:
 *   node build-presets.js
 * ========================================================================= */
'use strict';
const fs = require('fs');
const path = require('path');

const DIR = path.join(__dirname, 'presets');
const OUT = path.join(__dirname, 'presets-shared.js');

globalThis.XM = require('./model.js');
const XShare = require('./share.js');

function presetFromFile(text, fallbackName) {
  const got = XShare.fromFile(text);
  if (!got || !got.value) return null;
  const x = got.play && Object.keys(got.play).length ? got.play : null;
  if (got.kind === 'rig') {
    const entry = { rig: got.value };
    if (x) entry.x = x;
    return entry;
  }
  const entry = Object.assign(
    { template: [null, null, null, null, null, null, null] },
    got.value
  );
  if (x) entry.x = x;
  return entry;
}

function main() {
  if (!fs.existsSync(DIR)) fs.mkdirSync(DIR, { recursive: true });
  const files = fs.readdirSync(DIR).filter(f => f.toLowerCase().endsWith('.json'));

  const presets = {};
  for (const file of files) {
    const full = path.join(DIR, file);
    const name = path.basename(file, path.extname(file));
    let text;
    try { text = fs.readFileSync(full, 'utf8'); }
    catch (e) { console.warn(`skipped ${file}: could not read (${e.message})`); continue; }
    const entry = presetFromFile(text, name);
    if (!entry) { console.warn(`skipped ${file}: not a Xenachord layout file`); continue; }
    presets[name] = entry;
  }

  const names = Object.keys(presets).sort((a, b) => a.localeCompare(b));
  const head = `/* =====================================================================
 *  SHARED PRESETS — the layouts this app itself carries
 * =====================================================================
 *
 * GENERATED by build-presets.js from the presets/ folder.
 * ${new Date().toISOString().replace('T', ' ').slice(0, 19)} · ${names.length} preset${names.length === 1 ? '' : 's'}
 *
 * This file IS the preset list. It lives beside index.html, so every copy of
 * the app carries it and anybody who opens the app sees the same presets.
 *
 * TO ADD OR REMOVE A PRESET, use the presets/ folder, not this file:
 *   - drag a "Save Layout File (.json)" download into presets/ to add one
 *   - delete its file from presets/ to remove one
 *   - rename its file to rename the preset
 * then run \`node build-presets.js\` to regenerate this file. Each dropped
 * file already carries its tuning/notation and timbre/synth session, saved
 * exactly as Xenachord Designer wrote it.
 *
 * (This file can still be produced by the app's own "Write Presets File"
 * button, which overlays browser-side saves/deletions the same way. The two
 * paths write the same format and neither depends on the other.)
 */
`;
  const body = names
    .map(n => '  ' + JSON.stringify(n) + ': ' + JSON.stringify(presets[n]) + ',')
    .join('\n');
  const out = head + 'window.XENACHORD_PRESETS = {\n' + (body ? body + '\n' : '') + '};\n';

  fs.writeFileSync(OUT, out);
  console.log(`presets-shared.js written — ${names.length} preset${names.length === 1 ? '' : 's'} from presets/`);
}

main();
